### ISSUE TITLE
_index.scss is bad DX. Add partials/_partials.s[ca]ss lookup.

### ISSUE THREAD

**Issue by JohnAlbin** [at-import/node-sass-import-once#7]
Disclaimer: I've only read the README and not used this package.

But the "features" section says:

> Allows folders to contain an index file (index.scss, index.sass, _index.scss, _index.sass) that will automatically be imported if just the folder name is imported. For instance, `@import 'partials';` will try and import (_)partials.s(c|a)ss first, then partials/(_)index.s(c|a)ss.

This is bad developer experience. Can you imagine having multiple _index.scss files open? The editor tabs would all say the same thing. _blech_

Is there an option so that `@import 'partials';` imports a partials/(_)partials.s(c|A)ss file?

**Comment by Snugug** [comment]
This feature comes from https://github.com/sass/sass/issues/690

I've been using `_index.scss` on my current project and it's great. I don't find it particularly confusing because once I've got it open, I see what's going on in there. I also don't keep the `index` file open much, that's not my primary mode of working

That being said, I'm happy to add `(_)partials.s(c|a)ss` too. It should be an easy enough PR if you'd like to take a swing at it.

**Comment by oliverturner** [comment]
FWIW, I'm really liking the DX personally

**Comment by nathanjd** [comment]
This is my ideal developer experience as it directly matches NodeJS's module behavior. It would be great to use

```
@import 'partials'
```

Which would resolve to `./partials/_index.s(c|a)ss` or `./partials/index.s(c|a)ss` instead of

```
@import 'partials/partials'
```

or

```
@import 'partials/index'
```

Both of which I find to be redundant and can be more difficult to maintain.

As for the editor tabs, I use sublime and it will show as much path is necessary to delineate index.\* files. In my experience other editors do this as well. It works great for NPM packages (which resolve to `index.(js|json|node)`) by default).

This would be doubly effective when paired with module systems like NPM and a pre-compiler like gulp. For example, I am currently working on a project where we support modular sass within NPM packages by passing the sass source through a pre-compiler which allows for NodeJS module resolution in sass paths.

For example:

```
@import '@foo/package'
```

Would be compiled to:

```
@import '/full/path/node_modules/@foo/package'
```

We are also experimenting with crawling the javascript AST for required modules, then automatically generating a sass import file for all style dependencies in modules. Currently we have to add a "styles" attribute to each module's package.json. If this were standardized to look for a `index.scss` file, we could remove the "styles" attribute, resulting in a cleaner and more repeatable solution.

**Comment by JohnAlbin** [comment]
Given the dir/index name is from a core Sass feature request (not yet implemented), I withdraw this request for dir/dir.
